/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { Nfinity, NfinityInterface } from "../Nfinity";

const _abi = [
  {
    inputs: [
      {
        internalType: "string",
        name: "_name",
        type: "string",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "_eventId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "_purchaseId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "_by",
        type: "address",
      },
    ],
    name: "CustomerCheckedIn",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "_id",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "_extId",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "_by",
        type: "address",
      },
    ],
    name: "EventCancelled",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "_id",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "_extId",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "_by",
        type: "address",
      },
    ],
    name: "EventCompleted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "_id",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "_extId",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "_by",
        type: "address",
      },
    ],
    name: "EventCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "_id",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "_extId",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "_by",
        type: "address",
      },
    ],
    name: "EventSalesFinished",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "_id",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "_extId",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "_by",
        type: "address",
      },
    ],
    name: "EventSalesStarted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "_id",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "_extId",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "_by",
        type: "address",
      },
    ],
    name: "EventSalesSuspended",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "_id",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "_extId",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "_by",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "_settlement",
        type: "uint256",
      },
    ],
    name: "EventSettled",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "previousOwner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "_id",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "_extId",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "_by",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "_eventId",
        type: "uint256",
      },
    ],
    name: "PurchaseCancelled",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "_id",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "_extId",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "_by",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "_eventId",
        type: "uint256",
      },
    ],
    name: "PurchaseCompleted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "_id",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "_extId",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "_by",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "_eventId",
        type: "uint256",
      },
    ],
    name: "PurchaseRefunded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "_by",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "_settlement",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "_excess",
        type: "uint256",
      },
    ],
    name: "StoreClosed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "_by",
        type: "address",
      },
    ],
    name: "StoreOpen",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "_by",
        type: "address",
      },
    ],
    name: "StoreSuspended",
    type: "event",
  },
  {
    stateMutability: "payable",
    type: "fallback",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_eventId",
        type: "uint256",
      },
    ],
    name: "cancelEvent",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_purchaseId",
        type: "uint256",
      },
      {
        internalType: "string",
        name: "_externalId",
        type: "string",
      },
      {
        internalType: "string",
        name: "_customerId",
        type: "string",
      },
    ],
    name: "cancelPurchase",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_purchaseId",
        type: "uint256",
      },
    ],
    name: "checkIn",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "closeStore",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_eventId",
        type: "uint256",
      },
    ],
    name: "completeEvent",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "_externalId",
        type: "string",
      },
      {
        internalType: "address payable",
        name: "_organizer",
        type: "address",
      },
      {
        internalType: "string",
        name: "_name",
        type: "string",
      },
      {
        internalType: "uint256",
        name: "_storeIncentive",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_ticketPrice",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_ticketsOnSale",
        type: "uint256",
      },
    ],
    name: "createEvent",
    outputs: [
      {
        internalType: "uint256",
        name: "eventId",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_eventId",
        type: "uint256",
      },
    ],
    name: "endTicketSales",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_eventId",
        type: "uint256",
      },
    ],
    name: "fetchEventInfo",
    outputs: [
      {
        internalType: "uint256",
        name: "eventStatus",
        type: "uint256",
      },
      {
        internalType: "bytes32",
        name: "eventExternalId",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "eventOrganizer",
        type: "address",
      },
      {
        internalType: "string",
        name: "eventName",
        type: "string",
      },
      {
        internalType: "uint256",
        name: "eventStoreIncentive",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "eventTicketPrice",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "eventTicketsOnSale",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_eventId",
        type: "uint256",
      },
    ],
    name: "fetchEventSalesInfo",
    outputs: [
      {
        internalType: "uint256",
        name: "eventStatus",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "eventTicketsSold",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "eventTicketsLeft",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "eventTicketsCancelled",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "eventTicketsRefunded",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "eventTicketsCheckedIn",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "eventBalance",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "eventRefundableBalance",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_purchaseId",
        type: "uint256",
      },
    ],
    name: "fetchPurchaseInfo",
    outputs: [
      {
        internalType: "uint256",
        name: "purchaseStatus",
        type: "uint256",
      },
      {
        internalType: "bytes32",
        name: "purchaseExternalId",
        type: "bytes32",
      },
      {
        internalType: "uint256",
        name: "purchaseTimestamp",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "purchaseCustomer",
        type: "address",
      },
      {
        internalType: "bytes32",
        name: "purchaseCustomerId",
        type: "bytes32",
      },
      {
        internalType: "uint256",
        name: "purchaseQuantity",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "purchaseTotal",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "purchaseEventId",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "fetchStoreInfo",
    outputs: [
      {
        internalType: "address",
        name: "storeOwner",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "storeStatus",
        type: "uint256",
      },
      {
        internalType: "string",
        name: "storeName",
        type: "string",
      },
      {
        internalType: "uint256",
        name: "storeSettledBalance",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "storeExcessBalance",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "storeRefundableBalance",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "storeCounterEvents",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "storeCounterPurchases",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_account",
        type: "address",
      },
    ],
    name: "getAccountRole",
    outputs: [
      {
        internalType: "bool",
        name: "accountIsOwner",
        type: "bool",
      },
      {
        internalType: "bool",
        name: "accountIsOrganizer",
        type: "bool",
      },
      {
        internalType: "bool",
        name: "accountIsCustomer",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_customer",
        type: "address",
      },
    ],
    name: "getCountCustomerPurchases",
    outputs: [
      {
        internalType: "uint256",
        name: "countPurchases",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getCountCustomers",
    outputs: [
      {
        internalType: "uint256",
        name: "countCustomers",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_organizer",
        type: "address",
      },
    ],
    name: "getCountOrganizerEvents",
    outputs: [
      {
        internalType: "uint256",
        name: "countEvents",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getCountOrganizers",
    outputs: [
      {
        internalType: "uint256",
        name: "countOrganizers",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_index",
        type: "uint256",
      },
    ],
    name: "getCustomerByIndex",
    outputs: [
      {
        internalType: "address",
        name: "customer",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_organizer",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_index",
        type: "uint256",
      },
    ],
    name: "getEventIdByIndex",
    outputs: [
      {
        internalType: "uint256",
        name: "eventId",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_organizer",
        type: "address",
      },
    ],
    name: "getEventIdsByOrgazer",
    outputs: [
      {
        internalType: "uint256[]",
        name: "eventIds",
        type: "uint256[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_index",
        type: "uint256",
      },
    ],
    name: "getOrganizerByIndex",
    outputs: [
      {
        internalType: "address",
        name: "organizer",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_customer",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_index",
        type: "uint256",
      },
    ],
    name: "getPurchaseIdByIndex",
    outputs: [
      {
        internalType: "uint256",
        name: "purchaseId",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_customer",
        type: "address",
      },
    ],
    name: "getPurchaseIdsByCustomer",
    outputs: [
      {
        internalType: "uint256[]",
        name: "purchaseIds",
        type: "uint256[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "openStore",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_eventId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_quantity",
        type: "uint256",
      },
      {
        internalType: "string",
        name: "_externalId",
        type: "string",
      },
      {
        internalType: "uint256",
        name: "_timestamp",
        type: "uint256",
      },
      {
        internalType: "string",
        name: "_customerId",
        type: "string",
      },
    ],
    name: "purchaseTickets",
    outputs: [
      {
        internalType: "uint256",
        name: "purchaseId",
        type: "uint256",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_eventId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_purchaseId",
        type: "uint256",
      },
    ],
    name: "refundPurchase",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "renounceOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_eventId",
        type: "uint256",
      },
    ],
    name: "settleEvent",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_eventId",
        type: "uint256",
      },
    ],
    name: "startTicketSales",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "suspendStore",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_eventId",
        type: "uint256",
      },
    ],
    name: "suspendTicketSales",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    stateMutability: "payable",
    type: "receive",
  },
] as const;

export class Nfinity__factory {
  static readonly abi = _abi;
  static createInterface(): NfinityInterface {
    return new utils.Interface(_abi) as NfinityInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Nfinity {
    return new Contract(address, _abi, signerOrProvider) as Nfinity;
  }
}
